# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htZu-W6w561SWm2BU3Z9ve0E7Qriuj2g
"""

import pandas as pd

# Load dataset
df = pd.read_csv("student.csv")

# Create average column
df["average_marks"] = df[["math","science","programming"]].mean(axis=1)

# Top student
top_student = df.loc[df["average_marks"].idxmax()]
print("Top Performer:\n", top_student)

# Department-wise average
dept_avg = df.groupby("department")["average_marks"].mean()
print("\nDepartment Average:\n", dept_avg)

# Students below 60
low_students = df[(df["math"]<60) | (df["science"]<60) | (df["programming"]<60)]
print("\nStudents at Risk:\n", low_students)

# Correlation (attendance vs marks)
correlation = df["attendance"].corr(df["average_marks"])
print("\nCorrelation:", correlation)

import matplotlib.pyplot as plt

# Bar Chart - Student average
plt.bar(df["name"], df["average_marks"])
plt.title("Student Performance")
plt.xlabel("Students")
plt.ylabel("Average Marks")
plt.show()

# Department Performance
dept_avg.plot(kind='bar')
plt.title("Department Performance")
plt.show()

# Scatter Plot
plt.scatter(df["attendance"], df["average_marks"])
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.title("Attendance vs Marks")
plt.show()